[package]
name = "ftp-upload"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
crossterm = "0.25.0"
ftp = { version = "3.0" }
round = "0.1.2"