on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - run: |
          mv target/release/ftp-upload ftp-upload
          ./ftp-upload --help
          ./ftp-upload --dir test --user  ${{ secrets.USER }} --password  ${{ secrets.PWD }} --host  ${{ secrets.HOST }}
