on: [push]

name: CI

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - run: |
          mv target/release/ftp-upload ftp-upload
          ./ftp-upload --help
          ./ftp-upload --dir test --user  ${{ secrets.USER }} --password  ${{ secrets.PWD }} --host  ${{ secrets.HOST }}

  x86_64-unknown-linux-musl:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt update -y 
          sudo apt install -y zip build-essential musl-tools pkg-config libssl-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target x86_64-unknown-linux-musl
      - run: |
          mv target/x86_64-unknown-linux-musl/release/ftp-upload ftp-upload
          ./ftp-upload --help
          ./ftp-upload --dir test --user  ${{ secrets.USER }} --password  ${{ secrets.PWD }} --host  ${{ secrets.HOST }}
